apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: acc-data-update-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: acc-data-update-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /account/update_user
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /account/update_user
