include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-acml

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: acc-data-update-fn-05f38fac-dfcd-436b-8190-a225027ee4fa
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-acml
  environment:
    name: acc-data-update-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-03T12:12:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: acc-data-update-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: acc-data-update-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: acc-data-update-fn-05f38fac-dfcd-436b-8190-a225027ee4fa
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
